[2023-03-18T18:23:29.468+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: vehiclepositions.download_file manual__2023-03-18T18:23:27.285349+00:00 [queued]>
[2023-03-18T18:23:29.489+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: vehiclepositions.download_file manual__2023-03-18T18:23:27.285349+00:00 [queued]>
[2023-03-18T18:23:29.490+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T18:23:29.490+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-18T18:23:29.490+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T18:23:29.506+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_file> on 2023-03-18 18:23:27.285349+00:00
[2023-03-18T18:23:29.510+0000] {standard_task_runner.py:55} INFO - Started process 94179 to run task
[2023-03-18T18:23:29.516+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'vehiclepositions', 'download_file', 'manual__2023-03-18T18:23:27.285349+00:00', '--job-id', '761', '--raw', '--subdir', 'DAGS_FOLDER/vehiclepositions.py', '--cfg-path', '/tmp/tmpwpuv8rvf']
[2023-03-18T18:23:29.519+0000] {standard_task_runner.py:83} INFO - Job 761: Subtask download_file
[2023-03-18T18:23:29.624+0000] {task_command.py:388} INFO - Running <TaskInstance: vehiclepositions.download_file manual__2023-03-18T18:23:27.285349+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-18T18:23:29.727+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vehiclepositions
AIRFLOW_CTX_TASK_ID=download_file
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T18:23:27.285349+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-18T18:23:27.285349+00:00
[2023-03-18T18:23:29.847+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/melicharovykrecek/diploma/dags/vehiclepositions.py", line 46, in download_file
    f.write(response, sort_keys=True, indent=4)
TypeError: BufferedWriter.write() takes no keyword arguments
[2023-03-18T18:23:29.861+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=vehiclepositions, task_id=download_file, execution_date=20230318T182327, start_date=20230318T182329, end_date=20230318T182329
[2023-03-18T18:23:29.876+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 761 for task download_file (BufferedWriter.write() takes no keyword arguments; 94179)
[2023-03-18T18:23:29.889+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-18T18:23:29.925+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
