[2023-03-12T07:30:20.897+0000] {processor.py:153} INFO - Started process (PID=1462) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:30:20.898+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:30:20.899+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:30:20.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:30:20.928+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:30:20.927+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:30:20.929+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:30:20.929+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:30:20.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:30:20.943+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2023-03-12T07:31:02.810+0000] {processor.py:153} INFO - Started process (PID=1507) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:31:02.812+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:31:02.813+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:31:02.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:31:02.834+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:31:02.833+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:31:02.834+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:31:02.834+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:31:02.835+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:31:02.847+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:31:37.217+0000] {processor.py:153} INFO - Started process (PID=1560) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:31:37.219+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:31:37.220+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:31:37.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:31:37.240+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:31:37.239+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:31:37.240+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:31:37.240+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:31:37.240+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:31:37.252+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-12T07:32:13.209+0000] {processor.py:153} INFO - Started process (PID=1599) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:32:13.211+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:32:13.212+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:32:13.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:32:13.232+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:32:13.231+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:32:13.232+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:32:13.232+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:32:13.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:32:13.245+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:32:48.864+0000] {processor.py:153} INFO - Started process (PID=1638) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:32:48.866+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:32:48.866+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:32:48.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:32:48.887+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:32:48.886+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:32:48.887+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:32:48.887+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:32:48.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:32:48.900+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:33:28.764+0000] {processor.py:153} INFO - Started process (PID=1679) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:33:28.766+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:33:28.767+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:33:28.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:33:28.786+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:33:28.786+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:33:28.787+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:33:28.787+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:33:28.787+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:33:28.799+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-03-12T07:34:05.947+0000] {processor.py:153} INFO - Started process (PID=1715) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:34:05.949+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:34:05.950+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:34:05.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:34:05.970+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:34:05.969+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:34:05.970+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:34:05.970+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:34:05.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:34:05.983+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-12T07:34:43.736+0000] {processor.py:153} INFO - Started process (PID=1762) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:34:43.738+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:34:43.739+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:34:43.739+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:34:43.760+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:34:43.759+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:34:43.760+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:34:43.760+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:34:43.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:34:43.773+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:35:19.854+0000] {processor.py:153} INFO - Started process (PID=1823) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:35:19.855+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:35:19.856+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:35:19.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:35:19.877+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:35:19.877+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:35:19.878+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:35:19.878+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:35:19.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:35:19.890+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-12T07:35:55.766+0000] {processor.py:153} INFO - Started process (PID=1882) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:35:55.768+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:35:55.769+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:35:55.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:35:55.790+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:35:55.789+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:35:55.790+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:35:55.790+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:35:55.790+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:35:55.802+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-12T07:36:34.892+0000] {processor.py:153} INFO - Started process (PID=1919) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:36:34.894+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:36:34.895+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:36:34.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:36:34.916+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:36:34.915+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:36:34.916+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:36:34.916+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:36:34.916+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:36:34.929+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:37:10.241+0000] {processor.py:153} INFO - Started process (PID=1954) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:37:10.243+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:37:10.244+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:37:10.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:37:10.264+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:37:10.263+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:37:10.264+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:37:10.264+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:37:10.265+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:37:10.278+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:37:44.070+0000] {processor.py:153} INFO - Started process (PID=1989) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:37:44.072+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:37:44.073+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:37:44.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:37:44.095+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:37:44.094+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:37:44.095+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:37:44.095+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:37:44.095+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:37:44.107+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:38:22.089+0000] {processor.py:153} INFO - Started process (PID=2028) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:38:22.091+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:38:22.092+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:38:22.092+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:38:22.114+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:38:22.113+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:38:22.114+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:38:22.114+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:38:22.114+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:38:22.127+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:38:59.446+0000] {processor.py:153} INFO - Started process (PID=2074) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:38:59.450+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:38:59.451+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:38:59.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:38:59.472+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:38:59.472+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:38:59.473+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:38:59.473+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:38:59.473+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:38:59.486+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-03-12T07:39:37.345+0000] {processor.py:153} INFO - Started process (PID=2111) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:39:37.347+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:39:37.348+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:39:37.348+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:39:37.369+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:39:37.368+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:39:37.369+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:39:37.369+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:39:37.369+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:39:37.382+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:40:09.696+0000] {processor.py:153} INFO - Started process (PID=2155) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:40:09.698+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:40:09.699+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:40:09.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:40:09.722+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:40:09.721+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:40:09.723+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:40:09.723+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:40:09.723+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:40:09.736+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T07:40:44.403+0000] {processor.py:153} INFO - Started process (PID=2206) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:40:44.405+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:40:44.406+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:40:44.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:40:44.429+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:40:44.428+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:40:44.429+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:40:44.429+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:40:44.430+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:40:44.445+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-03-12T07:41:23.341+0000] {processor.py:153} INFO - Started process (PID=2268) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:41:23.343+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:41:23.344+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:41:23.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:41:23.366+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:41:23.365+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:41:23.366+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:41:23.366+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:41:23.366+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:41:23.380+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:41:57.144+0000] {processor.py:153} INFO - Started process (PID=2301) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:41:57.146+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:41:57.147+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:41:57.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:41:57.170+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:41:57.169+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:41:57.170+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:41:57.170+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:41:57.171+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:41:57.185+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-03-12T07:42:30.465+0000] {processor.py:153} INFO - Started process (PID=2335) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:42:30.466+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:42:30.467+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:42:30.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:42:30.489+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:42:30.488+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:42:30.489+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:42:30.489+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:42:30.489+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:42:30.502+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:43:05.553+0000] {processor.py:153} INFO - Started process (PID=2372) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:43:05.555+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:43:05.556+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:43:05.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:43:05.577+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:43:05.576+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:43:05.577+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:43:05.577+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:43:05.577+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:43:05.591+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:43:42.827+0000] {processor.py:153} INFO - Started process (PID=2427) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:43:42.829+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:43:42.830+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:43:42.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:43:42.853+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:43:42.853+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:43:42.854+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:43:42.854+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:43:42.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:43:42.868+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T07:44:21.829+0000] {processor.py:153} INFO - Started process (PID=2464) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:44:21.831+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:44:21.832+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:44:21.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:44:21.853+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:44:21.853+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:44:21.854+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:44:21.854+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:44:21.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:44:21.867+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:44:58.399+0000] {processor.py:153} INFO - Started process (PID=2503) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:44:58.402+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:44:58.403+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:44:58.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:44:58.425+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:44:58.424+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:44:58.426+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:44:58.426+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:44:58.426+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:44:58.441+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-03-12T07:45:32.327+0000] {processor.py:153} INFO - Started process (PID=2599) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:45:32.329+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:45:32.330+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:45:32.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:45:32.351+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:45:32.350+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:45:32.351+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:45:32.351+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:45:32.352+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:45:32.364+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:46:07.166+0000] {processor.py:153} INFO - Started process (PID=2637) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:46:07.168+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:46:07.169+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:46:07.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:46:07.190+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:46:07.190+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:46:07.191+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:46:07.190+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:46:07.191+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:46:07.204+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:46:44.935+0000] {processor.py:153} INFO - Started process (PID=2683) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:46:44.937+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:46:44.938+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:46:44.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:46:44.959+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:46:44.958+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:46:44.959+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:46:44.959+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:46:44.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:46:44.972+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:47:19.153+0000] {processor.py:153} INFO - Started process (PID=2716) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:47:19.155+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:47:19.156+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:47:19.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:47:19.179+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:47:19.178+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:47:19.179+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:47:19.179+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:47:19.179+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:47:19.192+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T07:47:55.731+0000] {processor.py:153} INFO - Started process (PID=2754) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:47:55.733+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:47:55.734+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:47:55.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:47:55.755+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:47:55.754+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:47:55.755+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:47:55.755+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:47:55.755+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:47:55.770+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T07:48:30.007+0000] {processor.py:153} INFO - Started process (PID=2787) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:48:30.009+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:48:30.010+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:48:30.009+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:48:30.031+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:48:30.030+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:48:30.031+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:48:30.031+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:48:30.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:48:30.046+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T07:49:10.616+0000] {processor.py:153} INFO - Started process (PID=2827) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:49:10.618+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:49:10.619+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:49:10.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:49:10.642+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:49:10.641+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:49:10.642+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:49:10.642+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:49:10.642+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:49:10.656+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T07:49:46.002+0000] {processor.py:153} INFO - Started process (PID=2861) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:49:46.003+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:49:46.004+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:49:46.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:49:46.025+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:49:46.024+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:49:46.025+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:49:46.025+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:49:46.026+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:49:46.038+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:50:19.664+0000] {processor.py:153} INFO - Started process (PID=2895) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:50:19.666+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:50:19.667+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:50:19.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:50:19.687+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:50:19.686+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:50:19.687+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:50:19.687+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:50:19.687+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:50:19.701+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:51:01.462+0000] {processor.py:153} INFO - Started process (PID=2941) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:51:01.464+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:51:01.465+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:51:01.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:51:01.487+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:51:01.486+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:51:01.487+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:51:01.487+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:51:01.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:51:01.501+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T07:51:39.421+0000] {processor.py:153} INFO - Started process (PID=2979) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:51:39.423+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:51:39.424+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:51:39.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:51:39.447+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:51:39.447+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:51:39.448+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:51:39.448+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:51:39.448+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:51:39.462+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-03-12T07:52:15.688+0000] {processor.py:153} INFO - Started process (PID=3015) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:52:15.690+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:52:15.691+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:52:15.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:52:15.712+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:52:15.712+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:52:15.713+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:52:15.713+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:52:15.713+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:52:15.726+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:52:48.441+0000] {processor.py:153} INFO - Started process (PID=3048) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:52:48.445+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:52:48.446+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:52:48.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:52:48.467+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:52:48.466+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:52:48.467+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:52:48.467+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:52:48.468+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:52:48.480+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T07:53:20.306+0000] {processor.py:153} INFO - Started process (PID=3079) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:53:20.308+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:53:20.308+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:53:20.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:53:20.331+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:53:20.330+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:53:20.331+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:53:20.331+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:53:20.331+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:53:20.345+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T07:53:53.402+0000] {processor.py:153} INFO - Started process (PID=3111) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:53:53.404+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:53:53.405+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:53:53.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:53:53.426+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:53:53.425+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:53:53.427+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:53:53.426+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:53:53.427+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:53:53.440+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:54:31.369+0000] {processor.py:153} INFO - Started process (PID=3146) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:54:31.371+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:54:31.372+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:54:31.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:54:31.393+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:54:31.392+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:54:31.393+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:54:31.393+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:54:31.393+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:54:31.407+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:55:04.518+0000] {processor.py:153} INFO - Started process (PID=3179) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:55:04.520+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:55:04.521+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:55:04.521+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:55:04.544+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:55:04.543+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:55:04.544+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:55:04.544+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:55:04.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:55:04.558+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T07:55:37.050+0000] {processor.py:153} INFO - Started process (PID=3211) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:55:37.052+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:55:37.053+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:55:37.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:55:37.074+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:55:37.073+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:55:37.074+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:55:37.074+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:55:37.074+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:55:37.088+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:56:12.100+0000] {processor.py:153} INFO - Started process (PID=3246) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:56:12.102+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:56:12.103+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:56:12.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:56:12.124+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:56:12.123+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:56:12.124+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:56:12.124+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:56:12.125+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:56:12.138+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:56:46.442+0000] {processor.py:153} INFO - Started process (PID=3280) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:56:46.443+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:56:46.444+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:56:46.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:56:46.464+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:56:46.464+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:56:46.465+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:56:46.465+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:56:46.465+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:56:46.478+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T07:57:20.749+0000] {processor.py:153} INFO - Started process (PID=3314) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:57:20.751+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:57:20.753+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:57:20.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:57:20.775+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:57:20.774+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:57:20.775+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:57:20.775+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:57:20.776+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:57:20.788+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T07:57:54.908+0000] {processor.py:153} INFO - Started process (PID=3346) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:57:54.910+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:57:54.911+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:57:54.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:57:54.932+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:57:54.931+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:57:54.932+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:57:54.932+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:57:54.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:57:54.946+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:58:33.881+0000] {processor.py:153} INFO - Started process (PID=3384) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:58:33.883+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:58:33.884+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:58:33.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:58:33.905+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:58:33.904+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:58:33.905+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:58:33.905+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:58:33.905+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:58:33.919+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T07:59:06.685+0000] {processor.py:153} INFO - Started process (PID=3417) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:59:06.686+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:59:06.687+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:59:06.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:59:06.708+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:59:06.707+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:59:06.708+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:59:06.708+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:59:06.708+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:59:06.721+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T07:59:41.356+0000] {processor.py:153} INFO - Started process (PID=3450) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:59:41.358+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T07:59:41.359+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:59:41.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:59:41.380+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:59:41.379+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T07:59:41.380+0000] {logging_mixin.py:137} INFO - [2023-03-12T07:59:41.380+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T07:59:41.380+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T07:59:41.393+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:00:17.298+0000] {processor.py:153} INFO - Started process (PID=3510) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:00:17.300+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:00:17.301+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:00:17.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:00:17.323+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:00:17.323+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:00:17.324+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:00:17.324+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:00:17.324+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:00:17.336+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T08:00:53.494+0000] {processor.py:153} INFO - Started process (PID=3552) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:00:53.495+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:00:53.496+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:00:53.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:00:53.519+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:00:53.518+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:00:53.519+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:00:53.519+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:00:53.519+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:00:53.533+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T08:01:30.299+0000] {processor.py:153} INFO - Started process (PID=3588) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:01:30.301+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:01:30.302+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:01:30.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:01:30.322+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:01:30.321+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:01:30.322+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:01:30.322+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:01:30.322+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:01:30.335+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T08:02:05.769+0000] {processor.py:153} INFO - Started process (PID=3622) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:02:05.771+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:02:05.773+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:02:05.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:02:05.794+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:02:05.794+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:02:05.795+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:02:05.795+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:02:05.795+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:02:05.807+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:02:41.251+0000] {processor.py:153} INFO - Started process (PID=3657) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:02:41.253+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:02:41.254+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:02:41.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:02:41.276+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:02:41.275+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:02:41.276+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:02:41.276+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:02:41.276+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:02:41.289+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:03:15.648+0000] {processor.py:153} INFO - Started process (PID=3690) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:03:15.650+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:03:15.651+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:03:15.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:03:15.674+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:03:15.673+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:03:15.674+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:03:15.674+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:03:15.674+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:03:15.687+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:03:51.943+0000] {processor.py:153} INFO - Started process (PID=3725) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:03:51.945+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:03:51.946+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:03:51.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:03:51.967+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:03:51.967+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:03:51.968+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:03:51.968+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:03:51.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:03:51.981+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:04:22.719+0000] {processor.py:153} INFO - Started process (PID=3756) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:04:22.721+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:04:22.722+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:04:22.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:04:22.744+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:04:22.743+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:04:22.744+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:04:22.744+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:04:22.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:04:22.757+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:04:59.764+0000] {processor.py:153} INFO - Started process (PID=3792) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:04:59.766+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:04:59.767+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:04:59.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:04:59.788+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:04:59.787+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:04:59.788+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:04:59.788+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:04:59.788+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:04:59.801+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:05:35.410+0000] {processor.py:153} INFO - Started process (PID=3826) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:05:35.412+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:05:35.412+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:05:35.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:05:35.433+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:05:35.432+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:05:35.434+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:05:35.434+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:05:35.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:05:35.447+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T08:06:13.901+0000] {processor.py:153} INFO - Started process (PID=3862) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:06:13.903+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:06:13.904+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:06:13.904+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:06:13.925+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:06:13.924+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:06:13.926+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:06:13.926+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:06:13.926+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:06:13.939+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:06:51.843+0000] {processor.py:153} INFO - Started process (PID=3900) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:06:51.845+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:06:51.846+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:06:51.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:06:51.867+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:06:51.866+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:06:51.867+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:06:51.867+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:06:51.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:06:51.880+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:07:28.916+0000] {processor.py:153} INFO - Started process (PID=3936) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:07:28.918+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:07:28.919+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:07:28.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:07:28.940+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:07:28.939+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:07:28.940+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:07:28.940+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:07:28.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:07:28.953+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:08:00.961+0000] {processor.py:153} INFO - Started process (PID=3997) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:08:00.962+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:08:00.963+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:08:00.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:08:00.985+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:08:00.984+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:08:00.985+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:08:00.985+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:08:00.985+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:08:00.999+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:08:35.930+0000] {processor.py:153} INFO - Started process (PID=4050) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:08:35.931+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:08:35.932+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:08:35.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:08:35.953+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:08:35.952+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:08:35.953+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:08:35.953+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:08:35.953+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:08:35.966+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-12T08:09:13.749+0000] {processor.py:153} INFO - Started process (PID=4086) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:09:13.751+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:09:13.752+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:09:13.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:09:13.773+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:09:13.773+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:09:13.774+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:09:13.774+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:09:13.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:09:13.788+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T08:09:52.593+0000] {processor.py:153} INFO - Started process (PID=4122) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:09:52.596+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:09:52.597+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:09:52.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:09:52.619+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:09:52.618+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:09:52.619+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:09:52.619+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:09:52.619+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:09:52.633+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T08:10:28.570+0000] {processor.py:153} INFO - Started process (PID=4158) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:10:28.573+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:10:28.574+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:10:28.574+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:10:28.596+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:10:28.595+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:10:28.596+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:10:28.596+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:10:28.597+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:10:28.610+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T08:11:08.153+0000] {processor.py:153} INFO - Started process (PID=4203) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:11:08.155+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:11:08.157+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:11:08.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:11:08.177+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:11:08.177+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:11:08.178+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:11:08.178+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:11:08.178+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:11:08.191+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:11:46.113+0000] {processor.py:153} INFO - Started process (PID=4254) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:11:46.115+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:11:46.118+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:11:46.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:11:46.139+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:11:46.139+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:11:46.140+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:11:46.140+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:11:46.140+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:11:46.155+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-03-12T08:12:24.388+0000] {processor.py:153} INFO - Started process (PID=4301) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:12:24.390+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:12:24.391+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:12:24.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:12:24.413+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:12:24.412+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:12:24.413+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:12:24.413+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:12:24.413+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:12:24.426+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T08:12:59.118+0000] {processor.py:153} INFO - Started process (PID=4350) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:12:59.121+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:12:59.122+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:12:59.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:12:59.144+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:12:59.143+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:12:59.145+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:12:59.144+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:12:59.145+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:12:59.159+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-03-12T08:13:38.544+0000] {processor.py:153} INFO - Started process (PID=4394) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:13:38.546+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:13:38.547+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:13:38.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:13:38.573+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:13:38.572+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:13:38.574+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:13:38.573+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:13:38.574+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:13:38.590+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2023-03-12T08:14:16.606+0000] {processor.py:153} INFO - Started process (PID=4450) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:14:16.608+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:14:16.610+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:14:16.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:14:16.637+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:14:16.636+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:14:16.637+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:14:16.637+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:14:16.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:14:16.658+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2023-03-12T08:14:53.147+0000] {processor.py:153} INFO - Started process (PID=4488) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:14:53.149+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:14:53.150+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:14:53.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:14:53.171+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:14:53.170+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:14:53.171+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:14:53.171+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:14:53.171+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:14:53.184+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-12T08:15:29.886+0000] {processor.py:153} INFO - Started process (PID=4523) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:15:29.888+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:15:29.889+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:15:29.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:15:29.912+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:15:29.911+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:15:29.912+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:15:29.912+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:15:29.913+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:15:29.925+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T08:16:08.379+0000] {processor.py:153} INFO - Started process (PID=4566) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:16:08.381+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:16:08.382+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:16:08.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:16:08.404+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:16:08.403+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:16:08.404+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:16:08.404+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:16:08.404+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:16:08.418+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:16:47.963+0000] {processor.py:153} INFO - Started process (PID=4603) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:16:47.964+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:16:47.965+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:16:47.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:16:47.988+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:16:47.987+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:16:47.988+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:16:47.988+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:16:47.988+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:16:48.001+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:17:30.638+0000] {processor.py:153} INFO - Started process (PID=4655) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:17:30.641+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:17:30.642+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:17:30.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:17:30.663+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:17:30.662+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:17:30.663+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:17:30.663+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:17:30.664+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:17:30.676+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:18:08.495+0000] {processor.py:153} INFO - Started process (PID=4691) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:18:08.497+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:18:08.499+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:18:08.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:18:08.521+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:18:08.520+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:18:08.521+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:18:08.521+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:18:08.521+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:18:08.535+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-12T08:18:42.735+0000] {processor.py:153} INFO - Started process (PID=4725) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:18:42.736+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:18:42.737+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:18:42.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:18:42.758+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:18:42.757+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:18:42.758+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:18:42.758+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:18:42.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:18:42.776+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-03-12T08:19:18.310+0000] {processor.py:153} INFO - Started process (PID=4761) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:19:18.312+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:19:18.314+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:19:18.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:19:18.338+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:19:18.337+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:19:18.338+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:19:18.338+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:19:18.338+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:19:18.354+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-03-12T08:19:53.807+0000] {processor.py:153} INFO - Started process (PID=4795) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:19:53.809+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:19:53.810+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:19:53.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:19:53.832+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:19:53.831+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:19:53.832+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:19:53.832+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:19:53.833+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:19:53.847+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-12T08:20:33.986+0000] {processor.py:153} INFO - Started process (PID=4840) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:20:33.988+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:20:33.990+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:20:33.989+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:20:34.010+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:20:34.010+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:20:34.011+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:20:34.011+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:20:34.011+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:20:34.024+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-03-12T08:21:19.103+0000] {processor.py:153} INFO - Started process (PID=4880) to work on /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:21:19.105+0000] {processor.py:743} INFO - Processing file /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-12T08:21:19.106+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:21:19.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:21:19.127+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:21:19.127+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-12T08:21:19.128+0000] {logging_mixin.py:137} INFO - [2023-03-12T08:21:19.128+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-12T08:21:19.128+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-12T08:21:19.140+0000] {processor.py:175} INFO - Processing /home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
